### ISSUE TITLE
🐛 Bug: Crash looking up packages for some maintainers: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/npm-username-to-packages#277]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`npx tidelift-me-up --username sboudrias` should retrieve data normally.

### Actual

```plaintext
npx tidelift-me-up --username sboudrias
file:///Users/josh/.npm/_npx/3874edfee03e1fcc/node_modules/npm-username-to-packages/lib/npmUsernameToPackages.js:11
    packages.push(...body.objects.map((result) => result.package));
                                  ^

TypeError: Cannot read properties of undefined (reading 'map')
    at npmUsernameToPackages (file:///Users/josh/.npm/_npx/3874edfee03e1fcc/node_modules/npm-username-to-packages/lib/npmUsernameToPackages.js:11:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async tideliftMeUp (file:///Users/josh/.npm/_npx/3874edfee03e1fcc/node_modules/tidelift-me-up/lib/tideliftMeUp.js:16:27)
    at async tideliftMeUpCli (file:///Users/josh/.npm/_npx/3874edfee03e1fcc/node_modules/tidelift-me-up/lib/cli/tideliftMeUpCli.js:47:28)
    at async file:///Users/josh/.npm/_npx/3874edfee03e1fcc/node_modules/tidelift-me-up/bin/index.js:4:1

Node.js v22.4.1
```

**Comment by JoshuaKGoldberg** [comment]
Adding a `console.log({ body })`:

```plaintext
 $ node test.js
{ body: { error: 'Service Unavailable' } }
file:///Users/josh/repos/npm-username-to-packages/lib/npmUsernameToPackages.js:12
    packages.push(...body.objects.map((result) => result.package));
```

Huh.

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @joshuakgoldberg for bug.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙
